### ISSUE TITLE
Не работает на последней ноде(10+)

### ISSUE THREAD

**Issue by PersonalityFox** [nikbelikov/20th-century#3]
Привет

Столкнулся с проблемой запуска галпа. Обновил ноду с 8 версии до 10lts (11 тоже пробовал) и галп отказался работать. Обновление версий пакетов до последней не принесло результата. 

Поковырялся и выяснил, что проблема кроется в файле `package-lock.json`. Т.к. удаление не влияет на функционал приложение — удаление самое простое решение. После всё заработало как нужно.

МР подготовить не могу, нет прав на создание веток в репе.

**Comment by nikbelikov** [comment]
День добрый!

Спасибо за информацию! Давно не смотрел, что в репке. Постараюсь актуализировать в ближайшее время :)

**Comment by nikbelikov** [comment]
@PersonalityFox fixed ;) https://github.com/nikbelikov/20th-century/commit/a394d2b293d0f146253cf8bbc8e338d1d34a8528
